# Generated by Django 6.0.2 on 2026-02-18 19:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Nombre del Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('measure_mm', models.PositiveIntegerField(db_index=True, verbose_name='Medida (mm)')),
                ('base_price_usd', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Precio base (USD)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalogo.product')),
            ],
            options={
                'verbose_name': 'Variante del Producto',
                'verbose_name_plural': 'Variantes del Producto',
                'ordering': ['product__name', 'measure_mm'],
                'indexes': [models.Index(fields=['product', 'measure_mm'], name='catalogo_pr_product_1af598_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'measure_mm'), name='uniq_variant_by_measure')],
            },
        ),
    ]
