# Generated by Django 6.0.2 on 2026-02-18 18:26

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='País')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='Código ISO')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Apellidos')),
                ('id_number', models.CharField(help_text='Cédula: 10 dígitos | RUC (persona natural): 13 dígitos (solo números)', max_length=13, unique=True, validators=[apps.core.validators.validate_ec_id], verbose_name='Cédula / RUC')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Número de Teléfono')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.CharField(db_index=True, max_length=120, verbose_name='Provincia')),
                ('city', models.CharField(db_index=True, max_length=120, verbose_name='Ciudad')),
                ('address_line', models.CharField(blank=True, default='', max_length=255, verbose_name='Domicilio / Dirección')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Dirección Principal')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clientes.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='clientes_cu_last_na_0f53a1_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['id_number'], name='clientes_cu_id_numb_db1b17_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['province', 'city'], name='clientes_ad_provinc_773556_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('customer',), name='uniq_primary_address_per_customer'),
        ),
    ]
