# Generated by Django 6.0.2 on 2026-02-18 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_customer_deleted_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='clientes_cu_id_numb_db1b17_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='clientes.country', verbose_name='País'),
        ),
    ]
