# Generated by Django 6.0.2 on 2026-03-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_customer_clientes_cu_id_numb_db1b17_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_primary', 'province', 'city'], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(help_text='Cédula: 10 dígitos | RUC (persona natural): 13 dígitos (solo números)', max_length=13, unique=True, verbose_name='Cédula / RUC'),
        ),
    ]
