# Generated by Django 6.0.2 on 2026-02-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0003_remove_customer_clientes_cu_id_numb_db1b17_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('CALL', 'Llamada')], default='WHATSAPP', max_length=20, verbose_name='Canal')),
                ('status', models.CharField(choices=[('DISPATCHED', 'Despachado'), ('CANCELLED', 'Cancelado'), ('PENDING', 'Pendiente')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('dispatched_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.customer', verbose_name='Cliente')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.address', verbose_name='Dirección de envío')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SALE', 'Venta'), ('PROMO', 'Promoción')], default='SALE', max_length=10, verbose_name='Tipo')),
                ('quantity_pairs', models.PositiveIntegerField(verbose_name='Cantidad (pares)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.order', verbose_name='Pedido')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.productvariant', verbose_name='Producto / Medida')),
            ],
            options={
                'verbose_name': 'Ítem del pedido',
                'verbose_name_plural': 'Ítems del pedido',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='pedidos_ord_status_b82fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'created_at'], name='pedidos_ord_custome_50ed3a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product_variant'], name='pedidos_ord_order_i_32f609_idx'),
        ),
    ]
