# Generated by Django 6.0.2 on 2026-02-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PRODUCTION', 'Producción'), ('SALE', 'Venta'), ('PROMO', 'Promoción'), ('ADJUSTMENT', 'Ajuste'), ('REVERSAL_SALE', 'Reverso de Venta (cancelación)'), ('REVERSAL_PROMO', 'Reverso de Promoción (cancelación)')], max_length=20, verbose_name='Tipo de movimiento')),
                ('quantity_pairs', models.IntegerField(help_text='Entradas positivas, salidas negativas', verbose_name='Cantidad (pares)')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
