# Generated by Django 6.0.2 on 2026-02-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovements',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='pedidos.order', verbose_name='Pedido relacionado'),
        ),
        migrations.AddField(
            model_name='inventorymovements',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.productvariant', verbose_name='Variante'),
        ),
    ]
