# Generated by Django 6.0.2 on 2026-02-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0002_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('PRODUCTION', 'Producción'), ('SALE', 'Venta'), ('PROMO', 'Promoción'), ('ADJUSTMENT', 'Ajuste'), ('REVERSAL_SALE', 'Reverso de Venta (cancelación)'), ('REVERSAL_PROMO', 'Reverso de Promoción (cancelación)')], max_length=20, verbose_name='Tipo de movimiento')),
                ('quantity_pairs', models.IntegerField(help_text='Entradas positivas, salidas negativas', verbose_name='Cantidad (pares)')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Nota')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='pedidos.order', verbose_name='Pedido relacionado')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='catalogo.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='InventoryMovements',
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product_variant', 'created_at'], name='inventario__product_427eae_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['order', 'created_at'], name='inventario__order_i_7c7dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='inventario__movemen_c70cf1_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.UniqueConstraint(condition=models.Q(('movement_type__in', ['REVERSAL_SALE', 'REVERSAL_PROMO'])), fields=('order', 'product_variant', 'movement_type'), name='uniq_reversal_per_order_variant_type'),
        ),
    ]
