# Generated by Django 6.0.2 on 2026-03-16 15:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Categoria de gasto',
                'verbose_name_plural': 'Categorias de gasto',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('expense_date', models.DateField(db_index=True, verbose_name='Fecha del gasto')),
                ('supplier_name', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Proveedor')),
                ('reference_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='gastos.expensecategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date', 'created_at'], name='gastos_expe_expense_faa6ee_idx'), models.Index(fields=['category', 'expense_date'], name='gastos_expe_categor_a976f9_idx'), models.Index(fields=['supplier_name', 'expense_date'], name='gastos_expe_supplie_dabd1c_idx')],
            },
        ),
    ]
